MelLightLevelDependence5sPulse_ND20_Analysis;
MelLightLevelDependence5sPulse_ND15_Analysis;
MelLightLevelDependence5sPulse_ND10_Analysis;
MelLightLevelDependence5sPulse_ND05_Analysis;
MelLightLevelDependence5sPulse_ND00_Analysis;

% Positive and negative pulses
MelLightLevelDependence5sBipolarPulse_ND10_Analysis;
MelLightLevelDependence5sBipolarPulse_ND15_Analysis;

% With cone noise
MelLightLevelDependence5sBipolarPulseConeNoise_ND10_Analysis;

% Assemble the data
Assemble_Traces;
Assemble_Traces_Bipolar;
Assemble_Traces_Bipolar_Individual;
Assemble_Traces_Bipolar_ConeNoise;
Assemble_Traces_Bipolar_ConeNoise_Individual;

% CRF
MelLightLevelDependence5sLMSPosConeNoiseCRF_ND10_Analysis; % LMS+
MelLightLevelDependence5sLMSNegConeNoiseCRF_ND10_Analysis; % LMS-
MelLightLevelDependence5sMelPosConeNoiseCRF_ND10_Analysis; % Mel+
MelLightLevelDependence5sMelNegConeNoiseCRF_ND10_Analysis; % Mel-